### ISSUE TITLE
readme: A way to detect disconnected clients

### ISSUE THREAD

**Issue by phomlish** [r3labs/sse#125]
go func() {
			// Received Browser Disconnection
			<-ctx.Done()
			println("The client is disconnected here")
			return
		}()

the golang compiler complains:
 undeclared name: ctx

**Comment by jamiesonbecker** [comment]
The `ctx` variable is the golang context variable that is provided by your web framework and is probably wrapped within the framework's own context variable. Usually there's a way to get access to the base golang context (i.e., something like WebContext.Context) -- check your web framework's documentation to learn how to access the original golang context.

**Comment by purehyperbole** [comment]
@phomlish 

Sorry for not responding sooner. There was a typo in the readme which I will fix. The correct code is:

```go
go func() {
	// Received Browser Disconnection
	<-r.Context().Done()
	println("The client is disconnected here")
	return
}()
```

**Comment by frederikhors** [comment]
I think we can close this now.

**Comment by phomlish** [comment]
That's working for me.  Is there a way to somehow match the connection that was disconnected to one that was opened?

**Comment by drewp** [comment]
You could look at r.RemoteAddr at these two points:

```
	mux.HandleFunc("/foo", func(w http.ResponseWriter, r *http.Request) {
		log.Println("client connects", r.RemoteAddr)
		go func() {
			<-r.Context().Done()
			log.Println("client disconnected", r.RemoteAddr)
		}()

		server.ServeHTTP(w, r)
	})
```

```
2022/12/01 15:09:01 client connects 127.0.0.1:52370
2022/12/01 15:09:02 client disconnected 127.0.0.1:52370
2022/12/01 15:09:02 client connects 127.0.0.1:52382
2022/12/01 15:09:03 client disconnected 127.0.0.1:52382
```
