### ISSUE TITLE
Examples ?

### ISSUE THREAD

**Issue by joeblew99** [r3labs/sse#13]
Would help.

Am thinking about using a MQ in the middle as well as using protocol buffers.

Also there is a good case for using this to allow golang channels to communicate over a network. It's a good match since golang channels require two endpoints as they are not bidirectional in the same way that SSE is not bidirectional.

Anyway if you have any example code etc or plans would be great to know

**Comment by Muddz** [comment]
No you do not need two end points to use SSE to communicate between parties of a network. You need a SSE (server) and a Client. As for inter-communicating between services, you are better of with just stick with MessageQueuing as this is what they are created for: Communication between services and servers.

**Comment by Muddz** [comment]
@purehyperbole I think you just can close this 3 years old question too
