### ISSUE TITLE
Streaming unsupported

### ISSUE THREAD

**Issue by mooijtech** [r3labs/sse#130]
Hello,

I am trying to setup SSE for a progress bar but I am getting "Streaming unsupported!" in FireFox.

Client:
```js
const source = new EventSource("http://localhost:1337/outlook/loading?stream=" + projectId, {withCredentials: true})
source.onmessage = e => console.log(e.data)
```

Server:
```go
func (server *Server) Start() {
	server.ServerSentEvents = sse.New()

	server.Router.HandleFunc("/outlook/loading", server.ServerSentEvents.ServeHTTP)
}
```
```go
go func() {
	server.ServerSentEvents.CreateStream(project.UUID)

	for percentage := range progressPercentageChannel {
		server.ServerSentEvents.Publish(project.UUID, &sse.Event{
			Data: []byte(fmt.Sprintf("%d%", percentage)),
		})
	}
}()
```

**Comment by mooijtech** [comment]
It seems like for some reason the http.ResponseWriter has no http.Flusher?

**Comment by mooijtech** [comment]
As per the documentation:
```
The default HTTP/1.x and HTTP/2 ResponseWriter implementations
support Flusher, but ResponseWriter wrappers may not.
```
I am using a [CORS wrapper](https://github.com/rs/cors):
```
	corsHandler := cors.New(cors.Options{
		AllowedOrigins:   []string{"http://localhost:3000", "http://127.0.0.1:3000"},
		AllowedMethods:   []string{http.MethodGet, http.MethodPost, http.MethodDelete},
		AllowCredentials: true,
	}).Handler(server.Router)

	Logger.Fatal(http.ListenAndServe(":1337", server.SessionManager.LoadAndSave(corsHandler)))
	```
	
Most likely this is the issue.

**Comment by mooijtech** [comment]
I need CORS otherwise the EventSource request will be blocked by CORS.

**Comment by mooijtech** [comment]
I'm still getting "Streaming unsupported!" even if I add the CORS header manually and remove the CORS library.

**Comment by mooijtech** [comment]
Maybe the [session manager](https://github.com/alexedwards/scs) doesn't support it?

**Comment by purehyperbole** [comment]
Hey @mooijtech ,

Please could you try and run this simpler example and see if it behaves correctly? I am unable to reproduce the issue you are seeing.

```go
package main

import (
	"time"
	"net/http"

	"github.com/r3labs/sse/v2"
)

func main() {
	s := sse.New()

	s.CreateStream("test")

	go func() {
		for {
			s.Publish("test", &sse.Event{Data: []byte("hello")})	
			time.Sleep(time.Second)	
		}
	}()

	s.Headers = map[string]string{
		"Access-Control-Allow-Origin": "*",
	}

	// Create a new Mux and set the handler
	mux := http.NewServeMux()
	mux.HandleFunc("/", s.ServeHTTP)

	http.ListenAndServe(":8080", mux)		
}
```

**Comment by mooijtech** [comment]
Hello,

Thanks for your response.
It seems to be an issue with the [session manager](https://github.com/alexedwards/scs) I'm using.
I have removed the server.SessionManager.LoadAndSave function and now it works.
It seems the session manager is wrapping http.ResponseWriter and apparently doesn't have the http.Flusher.

I will open an issue there.
