### ISSUE TITLE
sse can not get empty data like url opend with chrome

### ISSUE THREAD

**Issue by TuringZhu** [r3labs/sse#134]
url: `https://94.push2.eastmoney.com/api/qt/ulist/sse?secids=105.TSLA&fields=f2,f12,f14&invt=16&pz=16&pi=0&po=1&ut=d2ffaa6a585d612eda28417681d58fb&mpi=30000&`

retrun: `{"rc":102,"rt":1,"svr":2887283850,"lt":1,"full":1,"dlmkts":"","data":null}`
I opened the above `url` with Chrome, then it can get data every 9 seconds if `data` is null. but sse blocked and can not get new `{"rc":102,"rt":1,"svr":2887283850,"lt":1,"full":1,"dlmkts":"","data":null}`

can you tell me why it happened and how can I get new empty data like Chrome. I should know the connection is alive and confirm there is really no changed data come.

the above url  send changed data immediately if data changed else send empty data every 9 seconds.

**Comment by purehyperbole** [comment]
Hey @TuringZhu ,

It seems to work for me:

```go
package main

import (
	"fmt"
	"runtime"
	"github.com/r3labs/sse/v2"
)

func main() {
	c := sse.NewClient("https://94.push2.eastmoney.com/api/qt/ulist/sse?secids=105.TSLA&fields=f2,f12,f14&invt=16&pz=16&pi=0&po=1&ut=d2ffaa6a585d612eda28417681d58fb&mpi=30000&")
	
	err := c.SubscribeRaw(func(msg *sse.Event) {
		fmt.Println(string(msg.Data))
	})

	if err != nil {
		panic(err)
	}

	runtime.Goexit()
}
```

Could you please test the above and see if it works?

**Comment by TuringZhu** [comment]
Thank you for your answer. Before that I used `SubscribeChan`. After change to `SubscribeRaw `, it works ok.
