### ISSUE TITLE
Reconnect with exponential backoff?

### ISSUE THREAD

**Issue by didip** [r3labs/sse#14]
Hi all,

First of all, nice project. The API is nice and very intuitive.

That said, I'd like to propose a new feature where `client.go` `Subscribe` and `SubscribeChan` are capable of reconnecting indefinitely with exponential backoff.

The reason for this is because every http network is flaky. Connection is bound to be broken. So client should have a way to reliably reconnect.

What do you think?

**Comment by purehyperbole** [comment]
Hi Didip!

This sounds like something we'd like to have implement. Is this something you need urgently? 

I think we could look to add this, but it might not be for another week or two.

**Comment by didip** [comment]
It would be nice to have it, but I don’t need it urgently.

**Comment by fabianbaier** [comment]
+1

**Comment by adriacidre** [comment]
@didip & @fabianbaier this issue should be fixed now :)
