### ISSUE TITLE
SSE client randomly dies

### ISSUE THREAD

**Issue by fleaz** [r3labs/sse#141]
Hey,

thanks for this library. I used it recently to build [codemonauts/wikiwatch](https://github.com/codemonauts/wikiwatch) which is basically working fine but sometimes the client just dies and exits.

My stripped down main function looks like this
```
	client := sse.NewClient("https://stream.wikimedia.org/v2/stream/recentchange")

	err = client.Subscribe("recentchange", func(msg *sse.Event) {
		handleRecentChange(msg, config)
	})
	if err != nil {
		log.Error(err)
	}

	client.OnDisconnect(func(c *sse.Client) {
		log.Error("Disconnected!")
	})

	log.Error("Done")
```

This works for around 5-10 minutes (correctly processing all incoming events in that time, and then I get "Done" and the programm terminates. So I assume this is not a disconnect because the `OnDisconnect` function is not called, but also there is no error from `Subscribe` either.

How can I find out  what's the cause of this?

**Comment by purehyperbole** [comment]
Hey @fleaz thanks for raising the issue.

Looking at your example, `OnDiscconnect` won't be set up, as `Subscribe` is a blocking call. I would suggest setting up your `OnDisconnect` handler before subscribing and see if that returns anything useful.

**Comment by fleaz** [comment]
Sorry for the late reply. 

I moved the `OnDisconnect` handler to the top like you recommended and now the code is running fine since weeks (but still didn't print out anything 🙃)

I'm a bit  confused, but as long as it works without problems, I won't question it further and will close this for now.

Thanks :)
