### ISSUE TITLE
How do you stop receiving events from SubscribeChan()?

### ISSUE THREAD

**Issue by jeffreydwalter** [r3labs/sse#21]
If I want to stop receiving events from SubscribeChan can I just close the channel?

**Comment by purehyperbole** [comment]
Unfortunately, there isn't a safe way to do this with the current implementation of SubscribeChan. The go routine that reads from the channel will cause a panic if the channel is closed. 

Is it something that you need urgently? I can look at implementing Unsubscribe to kill the goroutine and close the channel.

**Comment by purehyperbole** [comment]
I've just merged functionality for the client. You should now be able to call client.Unsubscribe(chan), passing in the same channel that was used when subscribing.

It will safely stop the goroutine and close the channel for you.

**Comment by jbrawnjr** [comment]
If you call `client.Unsubscribe()`, the channel is closed, but the actual connection is not, so the server still registers it as being connected. This is problematic in situations where a needed action cannot be performed on the server until the client has disconnected. In `client.go`, in the `case` where you `return` out of the goroutine, if you add a call to `resp.Body.Close()`, the client disconnects properly.

**Comment by KianYang-Lee** [comment]
> If you call `client.Unsubscribe()`, the channel is closed, but the actual connection is not, so the server still registers it as being connected. This is problematic in situations where a needed action cannot be performed on the server until the client has disconnected. In `client.go`, in `SubscribeChan()`, in the `case` where you `return` out of the goroutine, if you add a call to `resp.Body.Close()`, the client disconnects properly.

@jbrawnjr  Is this issue resolved yet?
