### ISSUE TITLE
Decouple `stream` query parameter from Client module

### ISSUE THREAD

**Issue by campbellwmorgan** [r3labs/sse#29]
Firstly thanks a lot for this library! It's really great to have a well-tested SSE library out there in the go ecosystem.

I understand that the Client module was originally written to work with your Server module, but I would imagine that there are a few of us out there that would like to use the Client with other servers, in my case, Facebook.

Would it be possible to refactor the Subscribe code so that one could submit _optional_ flags for additional slugs / query params to extend the underlying `url`?

I would be happy to submit a PR for this.

Thanks

**Comment by purehyperbole** [comment]
Thanks, happy you like the library! 

This is actually something that has bugged me for a while. The stream functionality was included for internal usage at R3 Labs and maybe isn't all that useful to anyone else. 

I'm happy to expose functionality to allow custom query parameters, however i'm reluctant to change the default behaviour as i'm not sure who is dependant on that.

Would something like the following work for your usecase?:

```go
// define params as map 
params := map[string]string{
    "search": "example",
}

c := sse.NewClient("https://someurl")

// set query params, overwriting the default of stream = ?
c.SetQueryParams(params)
```

**Comment by purehyperbole** [comment]
I've implemented a few changes that keep the current interfaces intact, but allow you to specify what query params are set. 

The only caveat is that custom params will need to use `client.SubscribeRaw` and `client.SubscribeStreamRaw` to avoid having the params overwritten with the stream param.

Please let me know if this addresses your use case

Cheers

**Comment by campbellwmorgan** [comment]
@purehyperbole That looks awesome! Nice work and thanks for getting on this so quickly. Much appreciated!

My only comment is that on thinking about it, perhaps you are over-complicating it because I think [here](https://github.com/r3labs/sse/blob/28e9148b9de24da0594ff1b0cd9b1cbc64e07866/client.go#L94) the `query` variable will already contain all of the query options from the `URL` on the client struct, so in theory all you need is just an `if` clause so that an empty query parameter isn't given. 

Before I knew you were working on this, I did https://github.com/campbellwmorgan/sse/commit/a5e14a8d92fd0c65536a94076aa447fbde253277, but to make it readable you could use your `client.SubscribeRaw` which calls `client.Subscribe` with an empty `stream` variable?

**Comment by purehyperbole** [comment]
Sorry for the delayed response.

You're quite right. that works much better :)

 I'lll update the PR with those changes and merge.

Thanks again for the feedback
