### ISSUE TITLE
cErr is being shadowed in unit tests.

### ISSUE THREAD

**Issue by jeffreydwalter** [r3labs/sse#36]
Hey, was just looking through the unit test code today and noticed some code like this:
```
var cErr error
go func(cErr error) {
    cErr = c.Subscribe("test", func(msg *Event) {
        if msg.Data != nil {
            events <- msg
            return
       }
    })
}(cErr)
```

I didn't actually come across this failing, so I'm assuming here (with a little testing to back up my assumption)
Since your go routine is being passed an `error` it is being passed by value (i.e., copied), so when you set it in the go routine, you are actually setting a copy, and not the original cErr.

Check out this go playground example: https://play.golang.org/p/T_36FPCr3ei

If you agree it's broken, I'll submit a PR real quick.

Cheers,
Jeff

**Comment by purehyperbole** [comment]
Sorry for the late response!

You're correct that it is broken. That would have worked if the error was a pointer, however, it isnt implemented that way.

Thanks for the PR, i'll merge now.!
