### ISSUE TITLE
parameter in stream URL and reconnects

### ISSUE THREAD

**Issue by thekvs** [r3labs/sse#42]
Hi!

What would be the best way to support additional parameters that change their values quickly in stream's URL when re-connecting to the data source? For example in the WikiPedia's [EventStream](https://wikitech.wikimedia.org/wiki/EventStreams) we have `since=<timestamp>` parameter for consuming events from specified timestamp and I want to use the timestamp of the last processed event on reconnects.

**Comment by purehyperbole** [comment]
HI!

Apologies for the delayed response. 

URL Parameters are supported via the `client.URL` string. Are you manually disconnecting from the stream or is it as a result of a lost connection?

If it's the latter, there isn't currently a way to detect a disconnect. However, we could add a function that gets called on a disconnect that would allow you update the URL and its parameters.

Would something like this work for your usecase?

```go
client.OnDisconnect(func(c *sse.Client){
    c.URL = fmt.Sprintf("https://stream.wikimedia.org/v2/stream/recentchange?since=%s", time.Now().String())
}) 
```

**Comment by thekvs** [comment]
Hi!

Yes, it is the second case, i.e. disconnects on network issues etc. Your proposal about callback function looks like exactly what is needed in our case. Many thanks!

**Comment by purehyperbole** [comment]
I've implemented the functionality mentioned above on the `disconnect-callback` branch. Please would you be able to test it out and see if it fixes the issue you mentioned?

**Comment by thekvs** [comment]
Sorry for the delay.

I've tested `disconnect-callback` branch, it works perfectly. Please merge and consider making a new release.
