### ISSUE TITLE
Server is sending events with an empty data field, which violates the spec.

### ISSUE THREAD

**Issue by jeffreydwalter** [r3labs/sse#46]
According to the spec:
```
When the user agent is required to dispatch the event, then the user agent must act as follows:

1. If the data buffer is an empty string, set the data buffer and the event name buffer to the empty string and abort these steps.

...steps 2-5 omitted for brevity and clarity.

6. Queue a task to dispatch the newly created event at the EventSource object.
```

In this case, the server should NOT send the message if the Data field is empty. The current code in http.go is sending a message in this case. See https://github.com/r3labs/sse/blob/f81257c4e655c1c1aa58c18849fff04061d07c60/http.go#L67-L69

**Comment by purehyperbole** [comment]
Closing this issue as the mentioned PR has been merged.
