### ISSUE TITLE
panic: client.cleanup() closing sse.Event channel causing panic.

### ISSUE THREAD

**Issue by jeffreydwalter** [r3labs/sse#50]
Calling `close(ch)` in cleanup() causes a panic when `SubscribeChan()` on the same `sse.Event` object.

I'm not really sure what the "correct" way to handle this issue is... @purehyperbole any ideas?

The sample code from my last issue reproduces the problem:
```
package main

import (
    "log"

    "github.com/r3labs/sse"
)

const URL = "http://some.eventstream.url"

func main() {
    es := sse.NewClient(URL)
    events := make(chan *sse.Event)

    go func() {
        for {
            log.Println("HERE")
            go es.SubscribeChanRaw(events)
        }
    }()

    go func() {
        for {
            log.Println("HERE2")
            go es.SubscribeChanRaw(events)
        }
    }()

    done := make(chan interface{})

    <-done
}
```

**Comment by jeffreydwalter** [comment]
Would it make more sense to have the `sse.Event` be created inside the `NewClient()` method and have it be part of the client object, as opposed to passing it into the `Subscribe` functions?

**Comment by jeffreydwalter** [comment]
@purehyperbole what's the reasoning behind having the consumer of your library create the `sse.Event` object and the pass it into the `Subscribe` functions?

**Comment by jeffreydwalter** [comment]
Doing a little digging, it appears that closing channels is not required in go. According to [this S.O. article](https://stackoverflow.com/a/8593986), the authoritative answer is that closing a go channel is only required to signal to consumers that there is no more data.

**Comment by purehyperbole** [comment]
@jeffreydwalter thanks for looking into it. You're right that this channel close creates issues.

Theres two valid usecases I can think of that should be allowed:
1) allow subscription to two separate streams (on different clients with different URL's) and have them funnelled into one channel that can be consumed
2) having two consumers (each with their own channel) working on the same stream

I think removing the channel close is reasonable and should satisfy usecase 1 & 2. It's a user created channel, so it should be up to the user to handle channel cleanup.

I tend to reference github.com/nats-io/go-nats when it comes to things like this, and it seems they don't close the channel on an unsubscribe either.

#51 removes the channel close. I'll release once tests have passed.
