### ISSUE TITLE
Is there a way for a server to drop a message if it was not delivered within ...

### ISSUE THREAD

**Issue by mikamiel** [r3labs/sse#53]
First of all, great lib, thanks!
Is there a way for a server to drop a message if it was not delivered within a custom period of time?

**Comment by purehyperbole** [comment]
Hi, 

Are you after something that won't transmit old events to new or reconnecting clients?

Currently, events are cached on a per stream basis and all connected clients share that cache. Control over what messages are sent is left to the client though the `Last-Event-ID` header. 

Expiring old messages isn't supported, however I can look at adding an event TTL that would default any new or reconnecting clients that don't specify an `Last-Event-ID` to the oldest event that has not expired.

Would that fit your usecase?

**Comment by mikamiel** [comment]
> Expiring old messages isn't supported, however I can look at adding an event TTL that would default any new or reconnecting clients that don't specify an Last-Event-ID to the oldest event that has not expired.

Yes, that fits the bill mostly - event TTL!
And also it would be nice for an event to expire (on a server side) even if server could not deliver it to a **connected** client (in a limited amount of time) by whatever reason. But i don't know if it's even possible to track down an awaiting state of an object on a golang-channel on a sender side. May be track it somewhere earlier?

I'm trying to make a sort of send-pdfs-to-printer-over-TLS thing and want to make shure that stucked print jobs are being ruthlessly wiped out from a queu. Of course i can track it on a client side by timestamps but it's not an elegant way i believe (time syncronization between client and server, redundant net ping-pong etc).

**Comment by purehyperbole** [comment]
Ahh, I think I get you now :)

Could you please give the `event-ttl` branch  a test please? You can enable it like:

```go
s := server.New(...)
s.EventTTL = time.Second * 5
```

As implemented it should work with both connected and new/reconnecting clients.

**Comment by mikamiel** [comment]
Wow, faster than the speed of light, thank you very much! I'll give it a try tomorrow.

And i also have an idea of a small PR to your project. Of course if you'll consider it appropriate.
You'd have done it in a second, but anyway i wish to write it myself just to get some training ;)

**Comment by purehyperbole** [comment]
Happy to help! 

Awesome, PR's are definitely welcome. If you want any questions answered before you start work on it, please feel free to create an issue :)

**Comment by mikamiel** [comment]
Just tested event-ttl branch, everything works like a charm, thanks!

**Comment by purehyperbole** [comment]
awesome. Its now been merged. Thanks for the feedback!
