### ISSUE TITLE
Http endpoint doesn't return any response until first event is available on stream

### ISSUE THREAD

**Issue by tadovas** [r3labs/sse#57]
Affects all releases and master branch.
**Steps to reproduce:**
- Create event stream
- Try to access it by id on http endpoint

**Expected result:**
- Http response headers are sent immediatelly

**Actual result:**
- Http client is stuck forever waiting for http response.

The problem seems to be that http handler does the first flush only after it receives first event. It can be fixed by calling flush just before entering event loop. PR follows

**Comment by purehyperbole** [comment]
Thanks for raising the issue, I'll review the pull request now!
