### ISSUE TITLE
SSE only sends the first line of a multi-line String

### ISSUE THREAD

**Issue by Muddz** [r3labs/sse#62]
I have discovered a strange behavior. When sending a string with multiple lines, only the first line of that string is sent, the rest after a line-break doesn't gets sent. Is that an intended behavior to keep messages small?

**Here is an example from my server side:**

	sseServer.AutoReplay = false
	sseServer.BufferSize = 1024*30 //Increasing the BufferSize 30x more didn't help
	sseServer.CreateStream(sseID)

	sseServer.Publish(sseID, &sse.Event{
			Data: []byte("Hellloooooooooooooo\nWooooooooooooorld!!!"),
		})

**From the client end:**

	err := sse.NewClient(sseURL).Subscribe("sseID", func(msg *sse.Event) {
		log.Println(string(msg.Data))
	})

The received result in the Client side will be _"Hellloooooooooooooo"_

**Comment by purehyperbole** [comment]
Sorry for the delayed response.

This looks to be a result of the parser getting confused between the newline in the data message and those that are part of the protocol. 

For this reason, it's generally safer to base64 encode the contents of a message before sending them. This is provided by both the client and server by setting `EncodingBase64` to true.

**Comment by Muddz** [comment]
@purehyperbole Yes I have used base64 decoding-encoding to send larger Strings with multiple lines and it works fine. But is the behavior intended or will it be fixed in future updates?

**Comment by purehyperbole** [comment]
From reading the SSE specification again, it looks as if a message containing newline characters should be sent as multiple events, i.e.  `hello\n world` should be sent as:

```
data: hello
data: world
```

On the clients end, this should be recombined into a single event with the newline characters reinserted. Seeing as you're not seeing this behaviour, its correct to say this is a bug.

Unfortunately I don't have a huge amount of time to debug this, but I'll try and allocate some time this week to take a look.

**Comment by Muddz** [comment]
Okay nice to know, big appreciation for this library!

I would like to get an update on this issue when you begin to fix it
