### ISSUE TITLE
How to handle this error: "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by Muddz** [r3labs/sse#64]
I have an Windows .exe program written in Golang which use SSE to listen for events and write the SSE data strings into an .txt file. 

When the computer goes into hibernation/sleep mode and an event is received from the server, I get this error:

`read tcp 10.24.66.30:1824->52.56.35.14:8000: wsarecv: An existing connection was forcibly closed by the remote host.`

How do I handle this and why did this error happend?

**Comment by purehyperbole** [comment]
I'm not all that familiar with the ins and outs of windows networking, but in the situation you described, the connection gets killed by the host when it attempts to write to the TCP socket and there is no acknowledgement from the client. 

It most likely detects this connection as inactive and closes it. When the client attempts to perform a read when resuming from suspend, it will detect that the server has killed this connection.

Most OS's handle TCP connections this way to stop dead or inactive connections from holding on to the finite pool of file descriptors, so this error is actually expected.

The best way to handle this is to gracefully catch this error on the client and attempt to reconnect.

Hope that helps!

**Comment by Muddz** [comment]
@purehyperbole

**Comment by purehyperbole** [comment]
Sorry for the delay in getting back to you!

That error should actually be caught by the exponential backoff that's implemented by default. It should retry the subscription at different intervals until the tenth attempt when it finally returns the error.

I'm not sure why in your case the subsequent attempts are failing.

I would suggest when the error is returned from `sseClient.Subscribe()` that you set up a new subscription. So something like:

```go
for {
	err := sseClient.Subscribe("sseID", func(msg *sse.Event) {
		if len(msg.Data) < 1 {
			return
		}
	})

	if err == nil {
		return
	}

	// handle error
	...
}
```

**Comment by Muddz** [comment]
In case anyone Is having a simiilar problem, here is a nice solution to try reattempt subscription:

```
func startSSE() {
	for i := 0; i < 30; i++ { //30 attempts x 3 seconds delay between each
		if connectToSSE() {
			break
		}
		time.Sleep(time.Second * 3)
	}
}

func connectToSSE() bool {
	err := sseClient.Subscribe("sseID", func(msg *sse.Event) {
		//Do something with your received data
	})
	if err != nil {
		return false
	}
	return true
}
```
