### ISSUE TITLE
Will backOff keeps trying forever?

### ISSUE THREAD

**Issue by Muddz** [r3labs/sse#68]
Regarding this line: https://github.com/r3labs/sse/blob/master/client.go#L87

It seems as in this line the library tries forever to reconnect to the server in case one don't have internet connectin or can't reach the server. I'm right on my assumption?

Also when will `err` gets returned?

**Comment by purehyperbole** [comment]
Its entirely up to the back off strategy you use. If none is set, the default will be used. 

https://github.com/cenkalti/backoff/blob/v3/exponential.go#L36 indicates that it should be after ten successive failed attempts

**Comment by Muddz** [comment]
Yes its correct. I made two tests which returned the error after 15 and 17 minutes.  I will look into how I can make my own backOffStrategy to make a longere timeout time
