### ISSUE TITLE
SSE not working when app is behind Nginx.

### ISSUE THREAD

**Issue by Muddz** [r3labs/sse#73]
Has anyone managed to get their Go server app to work when its placed behind Nginx reverse-proxy setup in Ubuntu server?

I have followed these suggestions below without any success
[For Server-Sent Events (SSE) what Nginx proxy configuration is appropriate?
](https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate
)[EventSource / Server-Sent Events through Nginx](https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx)

My `POST `and `GET `requests work as intended, but when the server app needs to publish something out to clients, the clients never receives anything.

**Comment by Muddz** [comment]
According to one suggestion the app-server needs to add this header-value: ` X-Accel-Buffering: no;`
with these [headers here](https://github.com/r3labs/sse/blob/master/http.go#L24)

**Comment by purehyperbole** [comment]
I've implemented #74 which should allow you to specify headers like:

```go
s := sse.New()
s.Headers["X-Accel-Buffering"] = "no"
...
```

Please could you give it a try?

**Comment by Muddz** [comment]
@purehyperbole  It didn't do any difference

**Comment by Muddz** [comment]
@purehyperbole Forget the previous comment! **it did actually work** and I discovered why by pure randomness. The key was to restart the Client when deploying and starting the new server-binary with the changes. 

Why I only works when restarting the Client, is something I would to know why and I will do more testing. 

I will also try to not include the 'X-Accel-Buffering' header and try with pure Nginx configuration again where this time I restart the Client, so I have a full understanding of the issue

**Comment by purehyperbole** [comment]
Thanks for testing. I'll merge that PR now :smile:

**Comment by Muddz** [comment]
So far I have leared this:

- With no Nginx SSE configurations but with `X-Accel-Buffering: on` header on the SSE-server it works!

- Without  `X-Accel-Buffering: on ` header but with Nginx SSE configuration it also works

Regarding why the client has to be restarted when deploying or changing SSE on server-side is still something I will look into and if this issue only happends behind Nginx webserver

**Comment by Muddz** [comment]
@purehyperbole Everything in the library works as it should with regarding Nginx. If anyone in future have the same problem or similar, just point them to this issue.
