### ISSUE TITLE
can't upgrade to version 2.0.0+

### ISSUE THREAD

**Issue by paleozogt** [r3labs/sse#84]
```
➜  go get github.com/r3labs/sse@1.6.0
go: finding module for package gopkg.in/cenkalti/backoff.v1
go: found gopkg.in/cenkalti/backoff.v1 in gopkg.in/cenkalti/backoff.v1 v1.1.0

➜  go get github.com/r3labs/sse@v2.0.0
go get github.com/r3labs/sse@v2.0.0: github.com/r3labs/sse@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

I think this is because this project needs `v2` in the [import path](https://github.com/golang/go/wiki/Modules#faqs--semantic-import-versioning).

**Comment by purehyperbole** [comment]
@paleozogt Hi there, sorry for the delay in getting back to you.

I've updated the go mod file and implemented a v2 branch. Please could you let me know if this has resolved your issue?
