### ISSUE TITLE
server.Close() does not close clients connections

### ISSUE THREAD

**Issue by GreyXor** [r3labs/sse#93]
Hello @purehyperbole ,
I found out that [Server.Close()](https://github.com/r3labs/sse/blob/7824de9217d478a04eccaa259012d0514186a408/server.go#L49) does not close clients connections, which prevents me from doing a graceful shutdown of my net/http server

https://play.golang.org/p/qHxVR5W6xnA

To test:
1/ Execute program (there is 0 connections)
2/ Connect some client (with curl for example) (`curl "http://127.0.0.1:1337/stream?stream=messages"`)
3/ CTRL+C the server should call Server.Close() but the connections are still open

**Comment by purehyperbole** [comment]
Hey @GreyXor 

Thanks for raising the issue. It was caused by a cleanup function that was blocking the handler from exiting.

This should now be resolved on `v2.3.5`, please let me know if this fixes your issue.

**Comment by GreyXor** [comment]
Hi @purehyperbole,
i confirm that is fixed and clients are now correctly closed.
Thanks for the fast fix!
